// <auto-generated />
using System;
using MeterPulse.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeterPulse.Api.Migrations
{
    [DbContext(typeof(MeterPulseDbContext))]
    [Migration("20260501003924_ExpansionOfSchema")]
    partial class ExpansionOfSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("MeterPulse.Api.Models.BreachEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationMinutes")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EndTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EvidencePackId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FineAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PermitLimitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EvidencePackId");

                    b.HasIndex("MeterId");

                    b.HasIndex("PermitLimitId");

                    b.ToTable("BreachEvents");
                });

            modelBuilder.Entity("MeterPulse.Api.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinePerBreach")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("MeterPulse.Api.Models.EvidencePack", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("EvidencePacks");
                });

            modelBuilder.Entity("MeterPulse.Api.Models.Meter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Latitiude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WaterBodyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Meters");
                });

            modelBuilder.Entity("MeterPulse.Api.Models.MeterReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeterId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Reading")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MeterId");

                    b.ToTable("MeterReadings");
                });

            modelBuilder.Entity("MeterPulse.Api.Models.PermitLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("FineOverride")
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<int>("MeterId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherCondition")
                        .HasColumnType("TEXT");

                    b.Property<double?>("WeatherThresholdMm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MeterId");

                    b.ToTable("PermitLimits");
                });

            modelBuilder.Entity("MeterPulse.Api.Models.WeatherObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Parameter")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParameterName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Period")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Qualifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationReference")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnitName")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WeatherObservations");
                });

            modelBuilder.Entity("MeterPulse.Api.Models.BreachEvent", b =>
                {
                    b.HasOne("MeterPulse.Api.Models.EvidencePack", "EvidencePack")
                        .WithMany("BreachEvents")
                        .HasForeignKey("EvidencePackId");

                    b.HasOne("MeterPulse.Api.Models.Meter", "Meter")
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeterPulse.Api.Models.PermitLimit", "PermitLimit")
                        .WithMany()
                        .HasForeignKey("PermitLimitId");

                    b.Navigation("EvidencePack");

                    b.Navigation("Meter");

                    b.Navigation("PermitLimit");
                });

            modelBuilder.Entity("MeterPulse.Api.Models.Meter", b =>
                {
                    b.HasOne("MeterPulse.Api.Models.Company", "Company")
                        .WithMany("Meters")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MeterPulse.Api.Models.MeterReading", b =>
                {
                    b.HasOne("MeterPulse.Api.Models.Meter", "Meter")
                        .WithMany("Readings")
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("MeterPulse.Api.Models.PermitLimit", b =>
                {
                    b.HasOne("MeterPulse.Api.Models.Meter", "Meter")
                        .WithMany("PermitLimits")
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("MeterPulse.Api.Models.Company", b =>
                {
                    b.Navigation("Meters");
                });

            modelBuilder.Entity("MeterPulse.Api.Models.EvidencePack", b =>
                {
                    b.Navigation("BreachEvents");
                });

            modelBuilder.Entity("MeterPulse.Api.Models.Meter", b =>
                {
                    b.Navigation("PermitLimits");

                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
